### ISSUE TITLE
invalid artifact name for tag 1.0.0

### ISSUE THREAD

**Issue by ismaildem** [thorko/sensu-check-ceph#5]
Hi,
the artifact name sensu-check-ceph__linux_amd64.tar.gz in tag 1.0.0 is not valid. 
sensu-check-ceph__linux_amd64.tar.gz should be sensu-check-ceph_1.0.0_linux_amd64.tar.gz 

bonsai.sensu.io reports:
Version 1.0.0: missing GitHub release asset for sensu-check-ceph_1.0.0_linux_amd64.tar.gz

thx

**Comment by thorko** [comment]
release updated
