### ISSUE TITLE
bonsai reports still compilation errors

### ISSUE THREAD

**Issue by ismaildem** [thorko/sensu-check-ceph#6]
Hi thorko,

https://bonsai.sensu.io/ reports still compilation errors. Maybe you have to recompile the asset or create a new 
release.

"This asset has compilation errors
Version 1.0.0: missing GitHub release asset for sensu-check-ceph_1.0.0_linux_amd64.tar.gz"

thx

**Comment by thorko** [comment]
recompiled the asset on bonsai.sensu.io. 
let me know if it works

**Comment by ismaildem** [comment]
it works, thanx!

**Comment by thorko** [comment]
recompile worked
